### ISSUE TITLE
discord.py discontinued/not supported soon

### ISSUE THREAD

**Issue by Godnessy** [orhalimi/dojo-discord-bot#5]
We use discord.py library for our bot but according to this:
https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1#FAQ

The developer has suspended development on this library and the discord API will not be supporting it in the near future.
It seems the implementation of slash commands will make it impossible to use this library to further develop our bot.

**Comment by erantr1** [comment]
Problems are expected only for rather big projects with more than 100 servers.
At this point, we don't have such aspirations.
